# Problem 1: Reshaping for Image Processing
You are working on an image processing project, and you have a grayscale image represented as a 1D NumPy array **img_data** of size **(m * n)**, where m and n are the dimensions of the image. Write a function **reshape_image(img_data, new_shape)** that takes the original image data and a tuple representing the new shape **(p, q)** of the image. Ensure that the total number of pixels remains unchanged. If it's not possible to reshape without changing the total number of pixels, return **None**.

In [ ]:
# Write your function in this cell
import numpy as np

def reshape_image(img_data, new_shape):

    original_size = img_data.size
    new_size = new_shape[0] * new_shape[1]

    if original_size != new_size:
        return None

    reshaped_image = img_data.reshape(new_shape)
    return reshaped_image

img_data = np.arange(12)
new_shape = (4, 3)

reshaped_img = reshape_image(img_data, new_shape)

if reshaped_img is not None:
    print("Reshaped image:")
    print(reshaped_img)
else:
    print("Reshaping not possible.")


In [ ]:
import numpy as np

img_data = np.arange(9)  # Assuming a 3x3 image
new_shape = (3, 3)

result = reshape_image(img_data, new_shape)
print(result)

# Problem 2: Matrix Transpose
You are dealing with a dataset stored as a NumPy array **data_matrix** with dimensions **(m, n)**. Implement a function **transpose_matrix(data_matrix)** that returns the transpose of the given matrix.

In [9]:
# Write your function in this cell
import numpy as np
def transpose_matrix(data_matrix):
    return data_matrix.T

data_matrix = np.array([[1, 2, 3],
                        [4, 5, 6]])
print(data_matrix)
transposed_matrix = transpose_matrix(data_matrix)
print(transposed_matrix)



[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

data_matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = transpose_matrix(data_matrix)

print(transposed_matrix)

# Problem 3: Flattening for Data Processing
You have a 2D array representing data from different sensors. Write a function **flatten_sensor_data(sensor_data)** that takes a 2D NumPy array representing the sensor readings and returns a flattened 1D array.


In [ ]:
# Write your function in this cell
import numpy a np
def flatten_sensor_data(sensor_data):
    return sensor_data.flatten()
sensor_data = np.array([[10, 20, 30],
                        [40, 50, 60],
                        [70, 80, 90]])

flattened_data = flatten_sensor_data(sensor_data)
print(flattened_data)





In [7]:
import numpy as np
sensor_data = np.array([[10, 20, 30], [40, 50, 60]])
flattened_data = flatten_sensor_data(sensor_data)
print(flattened_data)




[[10 20 30]
 [40 50 60]]


NameError: name 'flatten_data' is not defined