# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

In [ ]:
import numpy as np
arr=np.arange(1,21,1).reshape(4,5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

In [ ]:
ones_array=np.ones((3,3))
print(ones_array)
zeros_array=np.zeros((2,4))
print(zeros_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

In [ ]:
# code here (you may create an array of your choice of size)
b=np.identity(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# code here (use the array createed in Question 1 for this)
empty=np.empty(5)
print(empty)
full=np.full(5,7)
print(full)
max=arr.max()
print(max)
min=arr.min()
print(min)
std=arr.std()
print(std)
mean=arr.mean()
print(mean)
var=arr.var()
print(var)
argmax=arr.argmax()
print(argmax)
linspace=np.linespace(0,1,5)
print(linspace)

[3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
[7 7 7 7 7]
20
1
5.766281297335398


5. Create the array below with a = np.arange(-15, 15).reshape(5, 6) ** 2

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

In [ ]:
# code here and try to figure out different functions on your own (as stated in Rule 3, also figure out how to propogate missing values as stated in Rule 4)
a=np.arange(-15,15).reshape(5,6) ** 2
print(a)

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]


In [ ]:
#RULE1
b=np.full(a.shape,3)
#rule2
print(a+b=/n')


6.Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [ ]:
# code here and display all 3 values appropriately. You MUST NOT choose an array of your own choice.
row-max=a.max(axis=1)
print(row_max)
mean=a.mean(axis=0)
print(mean)
min_postion=np.argmin(a)
print(min)


[link text](https://)# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING


In [ ]:
#code here # Create 2 arrays A and B with dim (5,4) and (5,) respectively, apply addition and subtraction.
A=np.radom.randint(0,10,(5,4))
A = np.array([1, 2, 3])       # Shape (3,)
B = np.array([[1], [2], [3]])  # Shape (3, 1)


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [ ]:
from itertools import accumulate
from functools import reduce
# Answer here (use both of these functions on an array of your own choice)
from functools import reduce
arr=np.array([1,2,3,4,5])
reduced_value=reduced(lambda x,y:x+y,arr)
accumulate_value=np.accumlate(arr)


### We will work with the following array:

In [ ]:
a = np.arange(25).reshape(5, 5)
a
#moving forward, you must use this array for the operations

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Use slicing only to select 3rd and last row along with 2nd and last columns:

In [ ]:
# Answer here
import numpy as np

# Example array
arr = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# Select the 3rd and last rows (rows with indices 2 and -1)
# Select the 2nd and last columns (columns with indices 1 and -1)
result = arr[[2, -1], :][:, [1, -1]]

print(result)


# Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [ ]:
# Answer here
import numpy as np

# Example larger array (5x5)
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

# To extract [[2, 3], [12, 13], [22, 23]]
# Rows: 0, 2, 4 (row indices 0, 2, 4)
# Columns: 2, 3 (column indices 2 and 3)
sub_array = arr[[0, 2, 4], 2:4]

print(sub_array)


# Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [ ]:
# Answer here
import numpy as np

# Example larger array (5x5)
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

# To extract [[6, 8], [16, 18], [21, 23]]
# Rows: 1, 3, 4 (row indices 1, 3, 4)
# Columns: 1, 3 (column indices 1 and 3)
sub_array = arr[[1, 3, 4], 1:4:2]

print(sub_array)


# Change the values 1, 10, 19 and 22 in the array to -2

In [ ]:
# Answer
import numpy as np

# Example array (5x5)
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

# Indices of values to be changed (1, 10, 19, and 22)
# We can locate their positions manually
indices = [(0, 1), (2, 0), (3, 4), (4, 2)]

# Change these specific elements to -2
for index in indices:
    arr[index] = -2

print(arr)


# Repeat above using boolean indexing

In [ ]:
# Answer here
import numpy as np

# Example array (5x5)
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

# Values to be changed: 1, 10, 19, 22
values_to_change = [1, 10, 19, 22]

# Create a boolean mask for these values
mask = np.isin(arr, values_to_change)

# Use boolean indexing to change the val


# Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [ ]:
# Answer here
import numpy as np

# Example larger array (5x5)
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

# Create a boolean mask for the rows you want to extract
# We want rows: 0, 2, 3 (for values 0, 10, and 15)
mask = np.array([True, False, True, True, False])

# Slice the columns: We want columns 0 and 3 (for values 0, 3, 10, 13, 15, 18)
sub_array = arr[mask, [0, 3]]

print(sub_array)


# Calculating the sum, min and max of all diagonal values


In [ ]:
# Answer here
import numpy as np

# Example array (5x5)
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

# Extract the diagonal values
diagonal_values = np.diagonal(arr)

# Calculate sum, min, and max of the diagonal values
diagonal_sum = np.sum(diagonal_values)
diagonal_min = np.min(diagonal_values)
diagonal_max = np.max(diagonal_values)

# Print the results
print("Diagonal values:", diagonal_values)
print("Sum of diagonal values:", diagonal_sum)
print("Minimum of diagonal values:", diagonal_min)
print("Maximum of diagonal values:", diagonal_max)



# Calculate the sum of differences between the 2nd row and 2nd last column

In [ ]:
row_2=a[1,:]
col_2_last=a[:,-2]
sum-diff=np.sum(row_2-col_2_last)
sum_diff

# Create a new array that is the sum of even rows and odd rows

In [ ]:
even_rows_sum=a[::2].sum(axis=1)
print(even_rows_sum)
odd_row_sum=a{1::2}.sum(axis=1)

## You are done. Good job!